{"uuid": "9e654512-fa2f-4001-964c-6697169dc958", "children": ["d5cf3a43-6d8c-4848-8419-0d6ee141a56e"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\trofimov-a\\PycharmProjects\\python_testing\\conftest.py\", line 28, in app\n    fixture = Application(browser=browser, base_url=web_config[\"baseUrl\"])\n  File \"C:\\Users\\trofimov-a\\PycharmProjects\\python_testing\\fixture\\application.py\", line 12, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 170, in __init__\n    RemoteWebDriver.__init__(\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\trofimov-a\\pycharmprojects\\python_testing\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1612814777769, "stop": 1612814815952}], "start": 1612814777769, "stop": 1612814816090}